# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HonBab' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HonBab
  pod 'Action'
  pod 'RxSwift', '~> 5.1.1'
  pod 'RxCocoa'
  pod 'RxViewController'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Kingfisher', '~> 6.0'
  pod 'KakaoSDK'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod 'naveridlogin-sdk-ios'
  pod 'NMapsMap'
  pod 'Firebase/Messaging'
  pod 'Alamofire'
  pod 'ObjectMapper'
end
